Class Kafka.Datatype.Deserializer Extends %String
{

Parameter DISPLAYLIST = ",StringDeserializer,IntegerDeserializer,LongDeserializer,DoubleDeserializer,ByteArrayDeserializer";

Parameter VALUELIST = ",org.apache.kafka.common.serialization.StringDeserializer,org.apache.kafka.common.serialization.IntegerDeserializer,org.apache.kafka.common.serialization.LongDeserializer,org.apache.kafka.common.serialization.DoubleDeserializer,org.apache.kafka.common.serialization.ByteArrayDeserializer";

}
